name: HUAWEI SWR IMAGE UPLOAD WITH REPO AND POLICY
author: Fredy Olarte 
branding:
  icon: upload-cloud
  color: orange
description: Create Docker images and push into a SWR repository. It can create it and attach a policy to store a max amount
inputs:
  huawei_access_key_id:
    description: The HUAWEI access key id
    required: true
  huawei_secret_access_key:
    description: The HUAWEI secret access key
    required: true
  swr_registry:
    description: The HUAWEI SWR Registry
    required: true
  repo:
    description: Name of your SWR repository
    required: true
  region:
    description: The HUAWEI region
    default: "la-south-2"
    required: true
  tags:
    description: Comma-separated string of SWR image tags
    default: "latest"
    required: false
  scan_images:
    description: Set this to true so you allow the repository to scan newly upload images
    default: "true"
    required: false
  dockerfile:
    description: Name of Dockerfile to use
    default: "Dockerfile"
    required: false
  extra_build_args:
    description: Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
    default: ""
    required: false
  path:
    description: Path to Dockerfile, defaults to the working directory
    default: "."
    required: false
  prebuild_script:
    description: Relative path from top-level to script to run before Docker build
    required: false
  behavior:
    description: Builds or just upload a previously build image
    default: "build"
    required: true
  image_name:
    description: Builds or just upload a previously build image
    required: false
  huawei_user:
    description: User Service Acount 
    required: true
  huawei_password:
    description: Password Service Acount 
    required: true
  huawei_domain:
    description: Domain Service Acount 
    required: true
  enpoint_token:
    description: Request address for calling token API
    default: "iam.myhuaweicloud.com" 
    required: true  
  enpoint_swr:
    description: Request address for calling swr API
    default: "swr-api.la-south-2.myhuaweicloud.com" 
    required: true
  swr_namespace:
    description: Your swr organization name
    required: true
    default: smu-chile
  swr_repos:
    description: Your swr image repository name. 
    required: true             
outputs:
  image:
    description: 'The created image name'
runs:
  using: docker
  image: Dockerfile
